name: Cucumber Test Report CI

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  report-verification:
    runs-on: ubuntu-latest
    name: Direct Execution Check
    steps:
      - uses: actions/checkout@v4
      - name: Execute Test Annotation Action
        uses: ./
        with:
          name: "Basic Cucumber Test Report"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.json"

  matrix-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension: ["json", "ndjson"]
    name: Matrix Cucumber Formats
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run cucumber || true
      - run: npm run cucumber-ok || true
      - run: npm run cucumber-undefined || true
      - run: npm run cucumber-non-failed || true
      - run: npm run cucumber-empty || true

      - name: Validate Failure Report
        uses: ./
        with:
          name: "${{ matrix.extension }}: Basic failure"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.${{ matrix.extension }}"

      - name: Skip Error Count in Title
        uses: ./
        with:
          name: "${{ matrix.extension }}: failure w/o count"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.${{ matrix.extension }}"
          show-number-of-error-on-check-title: false

      - name: Add All Warnings
        uses: ./
        with:
          name: "${{ matrix.extension }}: failure w/ all annotations"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.${{ matrix.extension }}"
          annotation-status-on-undefined: notice
          annotation-status-on-pending: notice

      - name: Undefined = Fail
        uses: ./
        with:
          name: "${{ matrix.extension }}: undefined = fail"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report-non-failed.${{ matrix.extension }}"
          check-status-on-undefined: failure
          annotation-status-on-undefined: failure

      - name: Pending = Fail
        uses: ./
        with:
          name: "${{ matrix.extension }}: pending = fail"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report-non-failed.${{ matrix.extension }}"
          check-status-on-pending: failure
          annotation-status-on-pending: failure

      - name: Errors = Neutral w/ Warnings
        uses: ./
        with:
          name: "${{ matrix.extension }}: neutral on error"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.${{ matrix.extension }}"
          check-status-on-error: neutral
          annotation-status-on-error: warning

      - name: Success OK
        uses: ./
        with:
          name: "${{ matrix.extension }}: OK success report"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report-ok.${{ matrix.extension }}"
          check-status-on-error: neutral
          annotation-status-on-error: warning

      - name: Empty Report Success
        uses: ./
        id: empty-success
        with:
          name: "${{ matrix.extension }}: empty report"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report-empty.${{ matrix.extension }}"

      - name: Show Summary
        uses: ./
        with:
          name: "${{ matrix.extension }}: full summary"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.${{ matrix.extension }}"
          show-global-summary-report: true

      - name: Validate Output
        if: steps.empty-success.outputs.cucumber-report-empty_failed_scenarios != 0
        run: exit 1

      - name: Job-Fail if Errors > 0
        id: check-failure
        continue-on-error: true
        uses: ./
        with:
          name: "${{ matrix.extension }}: job-failure rule"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report-non-failed.${{ matrix.extension }}"
          check-status-on-pending: failure
          annotation-status-on-pending: failure
          number-of-test-error-to-fail-job: 1

      - name: Ensure Failure Outcome
        if: steps.check-failure.outcome == 'failure'
        run: exit 0

      - name: Block if Job Did Not Fail
        if: steps.check-failure.outcome != 'failure'
        run: exit 1
